### ISSUE TITLE
ThreadFiber executes pending commands after dispose, PoolFiber does not

### ISSUE THREAD

**Issue by ex-ratt** [jetlang/core#1]
We've been using jetlang 0.2.5 for few years and decided to update all of the third party libraries used by our framework. After updating to version 0.2.12, some of our unit tests failed and I investigated the reasons.

The cause is a change from 2012 in `PoolFiber`. Since then, pending commands will not be executed anymore after calling `dispose()` on the fiber. This is in contrast to the `ThreadFiber`, that still executes pending commands. Is this an intentional difference in behaviour or just an unwanted side effect caused by a fix? Which kind of behavior should be expected from a fiber? Should all fibers behave the same way?

In our case, we have a callback that is called when the fiber is stopped. During and after this callback, no other commands should be executed. Until now, I cancelled all subscriptions and added the callback to the execution queue of the fiber, then disposed it. This still works with `ThreadFiber`, but not with `PoolFiber` (probably prevented by `isRunning` in https://github.com/jetlang/core/blob/master/src/main/java/org/jetlang/fibers/PoolFiber.java#L61). I fixed this by disposing the fiber only after the callback was invoked (using a `CountDownLatch` and blocking the calling thread), so for us, it is no big deal. I just wonder whether all fibers should behave the same way.

**Comment by mrettig** [comment]
For the PoolFiber AND ThreadFiber, there is no guarantee that the event
enqueued immediately before calling dispose actually gets executed. You
must use a CountDownLatch if you want to guarantee that final execution.

The change in the PoolFiber made it more likely that the consuming thread
won't have a chance to execute the event prior to dispose being called.
The ThreadFiber also could fail to execute the final event depending on if
it is currently processing other events.

Although the implementations are not identical, the behavior is the same in
that there is no guarantee that events enqueued before dispose always get
executed. The consuming thread stops ASAP, but that depends on whether it
is active or not and when it checks whether the fiber is still running.

BTW, when a fiber is disposed it automatically unsubscribes. You don't have
to manually unsubscribe unless you need fine grained control over the
subscription lifetime.

Mike

**Comment by ex-ratt** [comment]
Thanks for the clarification.

The subscription is cancelled manually to ensure that the stopping-callback is the last command executed by the fiber and no other callbacks may be invoked after that.
